# Generated by Django 4.0.5 on 2022-06-10 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='excerpt',
        ),
    ]
