# Generated by Django 4.0.5 on 2022-06-12 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_news_excerpt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={},
        ),
    ]
