# Generated by Django 4.0.5 on 2022-06-23 08:01

from django.db import migrations, models
import django.db.models.deletion
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('page', '0002_home'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('featured_image', versatileimagefield.fields.VersatileImageField(upload_to='images/gallery/featured/')),
                ('ppoi', versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20, verbose_name='Featured Images PPOI')),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gallery', to='page.home')),
            ],
            options={
                'verbose_name_plural': 'Galleries',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', versatileimagefield.fields.VersatileImageField(upload_to='images/gallery/')),
                ('ppoi', versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20, verbose_name='Gallery PPOI')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='images', to='gallery.gallery')),
            ],
        ),
    ]
