# Generated by Django 4.0.5 on 2022-06-17 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gallery', to='home.home'),
        ),
    ]
