# Generated by Django 4.0.5 on 2022-06-13 10:59

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_alter_gallery_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='ppoi',
            field=versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20, verbose_name='Gallery PPOI'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(upload_to='images/gallery/'),
        ),
    ]
