# Generated by Django 4.0.5 on 2022-06-13 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miscellaneous', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='miscellaneous',
            options={'verbose_name_plural': 'Miscellaneous'},
        ),
        migrations.RemoveField(
            model_name='miscellaneous',
            name='image',
        ),
        migrations.RemoveField(
            model_name='miscellaneous',
            name='ppoi',
        ),
        migrations.CreateModel(
            name='MiscellaneousImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/miscellaneous/')),
                ('miscellaneous', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='miscellaneous.miscellaneous')),
            ],
        ),
    ]
