# Generated by Django 4.0.5 on 2022-06-13 10:59

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('miscellaneous', '0002_alter_miscellaneous_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='miscellaneousimage',
            name='ppoi',
            field=versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20, verbose_name='Miscellaneous Images PPOI'),
        ),
        migrations.AlterField(
            model_name='miscellaneousimage',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(upload_to='images/miscellaneous/'),
        ),
    ]
