# Generated by Django 4.0.5 on 2022-06-12 07:09

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='syllabus',
            old_name='upload_pdf',
            new_name='upload_file',
        ),
        migrations.AddField(
            model_name='syllabus',
            name='content',
            field=ckeditor.fields.RichTextField(default=''),
            preserve_default=False,
        ),
    ]
