# Generated by Django 4.0.5 on 2022-06-12 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0002_rename_upload_pdf_syllabus_upload_file_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='syllabus',
            old_name='upload_file',
            new_name='file',
        ),
    ]
