# Generated by Django 4.0.5 on 2022-06-12 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0003_rename_upload_file_syllabus_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='syllabus',
            name='slug',
            field=models.SlugField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
