# Generated by Django 4.0.5 on 2022-06-12 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0004_syllabus_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syllabus',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
