# Generated by Django 4.0.5 on 2022-06-14 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board_members', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boardmembers',
            options={'verbose_name_plural': 'Board Members'},
        ),
    ]
