# Generated by Django 4.0.5 on 2022-06-14 06:35

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='slug',
        ),
        migrations.AddField(
            model_name='about',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='images/about/'),
        ),
        migrations.AddField(
            model_name='about',
            name='ppoi',
            field=versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20, verbose_name='About Image PPOI'),
        ),
    ]
