# Generated by Django 4.0.5 on 2022-06-22 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='content_type',
            field=models.ForeignKey(blank=True, help_text='Please select the type of the menu item, e.g. about or gallery.', limit_choices_to={'model__in': ['miscellaneous', 'about', 'board_member']}, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
